### ISSUE TITLE
Implement DBcc

### ISSUE THREAD

**Issue by marhel** [marhel/r68k#2]
Please implement the instruction for Test Condition, Decrement, and Branch. See implementation of Bcc. For more information, please read the [instruction contribution guidelines](https://github.com/marhel/r68k/wiki/contributing)

**Comment by marhel** [comment]
I'll take this one next.

**Comment by emoon** [comment]
:+1:

**Comment by marhel** [comment]
I pushed an implementation of this op, but it fails qc tests for DBF due to a presumed cycle bug in Musashi. I have submitted a PR to fix that (kstenerud/Musashi#12). I'll close this issue when the PR is merged, and I've updated the bundled Musashi lib.

**Comment by emoon** [comment]
:+1:
